name: Run watch_momentum_signals

on:
  schedule:
    # JST 15:15 = UTC 06:15
    - cron: "15 6 * * 1-5"
  workflow_dispatch:  # ← 手動実行ボタンを有効にする

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python watch_momentum_signals.py
